version: "3.9"

services:
  back:
    build: .
    container_name: myapiback
    ports:
      - "7825:5000"
    command: ["flask", "run", "--host=0.0.0.0", "-p 5000"]
    volumes:
      - ./app:/tmp/app
      - ./.data:/tmp/.data