apiVersion: v1
kind: Service
metadata:
  name: myapiback2-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - nodePort: 31479
      port: 7825
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapiback2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: myapiback2
          image: 176352050582.dkr.ecr.us-east-1.amazonaws.com/myapiback2:latest
          ports:
            - containerPort: 5000